### ISSUE TITLE
concurrent.futures._base.TimeoutError

### ISSUE THREAD

**Issue by llllly26** [bytedance/ConfDiff#3]
I encounter an issue, when I preprocess the `rcsb `data and run `process_mmcif_metadata.py`.
I don't know which sample has the problem, how to solve it? thanks!

```
Traceback (most recent call last):
  File "confdiff/ConfDiff/src/utils/misc/process.py", line 110, in mp_with_timeout
    result = next(result_itr)
  File "/home/ubuntu/anaconda3/envs/confdiff/lib/python3.9/site-packages/pebble/pool/base_pool.py", line 224, in next
    raise result
  File "/home/ubuntu/anaconda3/envs/confdiff/lib/python3.9/site-packages/pebble/pool/base_pool.py", line 264, in chunk_result
    return future.result(timeout=timeout)
  File "/home/ubuntu/anaconda3/envs/confdiff/lib/python3.9/concurrent/futures/_base.py", line 448, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/confdiff/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/confdiff/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "confdiff/ConfDiff/datasets/rcsb/process_mmcif_metadata.py", line 359, in <module>
    main(args)
  File "confdiff/ConfDiff/datasets/rcsb/process_mmcif_metadata.py", line 280, in main
    results = mp_with_timeout(
  File "confdiff/ConfDiff/src/utils/misc/process.py", line 117, in mp_with_timeout
    f"Timeout {error.args[1]} s: {error_report_fn(current_ix)}"
IndexError: tuple index out of range
```

**Comment by ynshen** [comment]
@llllly26 it seems `error.args` returns an empty tuple. For a temporarily fix, can you try removing the error massage? It shall print out the `current_ix` of the timeout data.

Like this:
```python
# line 117: original 
f"Timeout {error.args[1]} s: {error_report_fn(current_ix)}"
# line 117: fix
f"Timeout: {error_report_fn(current_ix)}"
```

**Comment by Zadak-H** [comment]
is there any way to fix this problem I am getting this same problem error?
